Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/trusty64'
  config.vm.provider 'virtualbox' do |vb|
    # メモリが不足するとリンカがエラー終了する
    # 1024MBでは足りなかった
    vb.memory = 2048 # MB
  end
  config.vm.provision :file,
                      source: 'AppRun',
                      destination: 'AppRun'
  config.vm.provision :file,
                      source: 'mikutter.desktop',
                      destination: 'mikutter.desktop'
  config.vm.provision :shell,
                      path: 'install_dependencies.sh',
                      privileged: false
  config.vm.provision :shell,
                      path: 'gen_appimage.sh',
                      env: {
                        REVISION: ENV['REVISION'],
                        VOLUME: '/vagrant',
                      },
                      privileged: false
end
