Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/trusty64'
  config.vm.provider 'virtualbox' do |vb|
    # メモリが不足するとリンカがエラー終了する
    # 1024MBでは足りなかった
    vb.memory = 2048 # MB
  end
  config.vm.provision 'file',
                      source: 'AppRun',
                      destination: 'AppRun'
  # TODO: mikutter.desktopを適当な場所に移動する
  config.vm.provision 'file',
                      source: 'mikutter.desktop',
                      destination: 'mikutter.desktop'
  config.vm.provision 'file',
                      source: 'no-sslv3-patch.diff',
                      destination: 'no-sslv3-patch.diff'
  config.vm.provision 'shell',
                      path: 'gen_appimage.sh',
                      env: { REVISION: ENV['REVISION'] },
                      privileged: false
end
